POST http://localhost:3000/api/devices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTc3MDIxMjcwMSwiZXhwIjoxNzcwMjQxNTAxfQ.eTc6fwEtKSUDl2eXm2hcn5kKvorFEoyncG3kUfvskZY
Content-Type: application/json

{
  "device_id_logic": "ESP32-TEST-001",
  "mac": "AA:BB:CC:DD:EE:FF",
  "alias": "Dispositivo de Manolo",
  "status": "active",
  "user_id": 4
}

###
GET http://localhost:3000/api/devices/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTc3MDIxMjcwMSwiZXhwIjoxNzcwMjQxNTAxfQ.eTc6fwEtKSUDl2eXm2hcn5kKvorFEoyncG3kUfvskZY

###
PUT http://localhost:3000/api/devices/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTc3MDIxMjcwMSwiZXhwIjoxNzcwMjQxNTAxfQ.eTc6fwEtKSUDl2eXm2hcn5kKvorFEoyncG3kUfvskZY
Content-Type: application/json

{
  "alias": "Dispositivo actualizado",
  "status": "Inactive"
}


###
PATCH http://localhost:3000/api/devices/3/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTc3MDIxMjcwMSwiZXhwIjoxNzcwMjQxNTAxfQ.eTc6fwEtKSUDl2eXm2hcn5kKvorFEoyncG3kUfvskZY
Content-Type: application/json

{
  "status": "active"
}

###
DELETE http://localhost:3000/api/devices/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTc3MDIxMjcwMSwiZXhwIjoxNzcwMjQxNTAxfQ.eTc6fwEtKSUDl2eXm2hcn5kKvorFEoyncG3kUfvskZY