POST http://localhost:3000/api/devices
//Authorization: Bearer 
Content-Type: application/json

{
  "device_id_logic": "ESP32-TEST-001",
  "mac": "AA:BB:CC:DD:EE:FF",
  "alias": "Dispositivo de Manolo",
  "status": "active",
  "user_id": 4
}

###
GET http://localhost:3000/api/devices/3
//Authorization: Bearer 

###
PUT http://localhost:3000/api/devices/3
//Authorization: Bearer 
Content-Type: application/json

{
  "alias": "Dispositivo actualizado",
  "status": "Inactive"
}


###
PATCH http://localhost:3000/api/devices/3/status
//Authorization: Bearer 
Content-Type: application/json

{
  "status": "active"
}

###
DELETE http://localhost:3000/api/devices/3
//Authorization: Bearer 