###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "manolo@gmail.com",
  "password": "Manolo1234!",
  "name": "Manolo",
  "surnames": "Pérez López",
  "date_born": "1950-05-20",
  "phone_num": "+34600111222"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "isabel@gmail.com",
  "password": "Isabel1234!",
  "name": "Isabel",
  "surnames": "Pérez López",
  "date_born": "1950-05-20",
  "phone_num": "+34600111444"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "marta@gmail.com",
  "password": "Marta1234!",
  "name": "Marta",
  "surnames": "Rövanpera",
  "date_born": "1950-05-20",
  "phone_num": "+34600111124"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "carlos@gmail.com",
  "password": "Carlos1234!",
  "name": "Carlos",
  "surnames": "Med Vades",
  "date_born": "1956-02-20",
  "phone_num": "+34600114591"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "Admin1234!",
  "name": "Admin",
  "phone_num": "+34600111223"

}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "Admin1234!"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "marta@gmail.com",
  "password": "Marta1234!"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "isabel@gmail.com",
  "password": "Isabel1234!"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "carlos@gmail.com",
  "password": "Carlos1234!"
}

### registro incorrecto
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "usuario1@test.com",
  "password": "Test1234!",
  "name": "Juan"
}

### contraseña incorrecta
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "usuario1@test.com",
  "password": "Test"
}

### inicio correcto
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "manolo@gmail.com",
  "password": "Manolo1234!"
}

### registro dispositivo
### Crear Dispositivo (Con Token) el token se manda sin las comillas ""
POST http://localhost:3000/api/devices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTc3MDg4ODI0NCwiZXhwIjoxNzcwOTE3MDQ0fQ.uyCkfMcqjb1Vyy4sGWbYqmfYydYUcNbecG0NovRmDIc

{
  "device_id_logic": "38182B841494",
  "mac": "38:18:2B:84:14:94",
  "alias": "ESP32 Prototipo",
  "status": "active",
  "user_id": 1
}

### Enviar Telemetría (Ruta y Puerto corregidos)
POST http://localhost:3000/api/auth/telemetry
Content-Type: application/json

{
  "deviceId": "38182B841494",
  "accX": 0.45,
  "accY": -0.12,
  "accZ": 9.81,
  "fallDetected": false
}


### Enviar Telemetría VERCEL (Ruta y Puerto corregidos)
https://falldetectionsystem.vercel.app/api/auth/telemetry
Content-Type: application/json

{
  "deviceId": "38182B841494",
  "accX": 0.45,
  "accY": -0.12,
  "accZ": 9.81,
  "fallDetected": false
}